#!/bin/sh -e

pr() {
    poetry run python -m "$@"
}

cat pyproject.toml

pr pytest -s --cov-report term-missing --cov-report=xml:coverage.xml --cov=arq_prometheus "${1:-tests}"
pr black arq_prometheus tests --check
pr isort --check-only arq_prometheus tests
pr pflake8 arq_prometheus/ tests/
pr mypy arq_prometheus/ tests/
